apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: "{{ .Release.Namespace }}"
data:
  # This script runs during MySQL initialization
  01-init-database.sql: |
    CREATE DATABASE app_db;
    CREATE USER 'app_user'@'%' IDENTIFIED BY 'app_password';
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    FLUSH PRIVILEGES;
