apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-init-scripts
  namespace: "{{ .Release.Namespace }}"
data:
  # This script can be used for additional initialization if needed
  01-init-database.sql: |
    -- Create default database if it doesn't exist
    IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'default_db')
    BEGIN
        CREATE DATABASE default_db;
    END
    GO

    USE default_db;
    GO
